services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Admin-181020"
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql
      - /home/facurodrij/PycharmProjects/stockcar-gestion/Datos_FullBackup_20240418_0803.bak:/var/opt/mssql/backup/Datos_FullBackup_20240418_0803.bak
  psql:
    image: postgres:16.2
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Admin-181020"
      POSTGRES_DB: "erp"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  db_data:
  pgdata: